name: Deploy Docker

# Run workflow on tags starting with v (eg. v2, v1.2.0)
on: workflow_dispatch

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true # Will only build if this is not here
          tags: |
            ghcr.io/${{ github.repository }}:${{github.run_number}}
           
      #- name: run docker and push
       # run: |
       #   docker build -f ./Dockerfile . -t test:${{github.run_number}} --build-arg NODE_AUTH_TOKEN=$NODE_AUTH_TOKEN
       #   docker tag test:${{github.run_number}} ghcr.io/ghcr-install/test:${{github.run_number}}
       #   docker push ghcr.io/ghcr-install/test:${{github.run_number}}
       # shell: bash
          
      - name: list image
        run: |
          docker image ls -a
        shell: bash
        
      #- name: Delete image
       # uses: bots-house/ghcr-delete-image-action@v1.0.0
       # with:
       #   # NOTE: at now only orgs is supported
       #   owner: bots-house
       #   name: some-web-service
       #   # NOTE: using Personal Access Token
       #   token: ${{ secrets.REGISTRY_TOKEN }}
       #   tag: ghcr.io/${{ github.repository }}:${{github.run_number}}
          
      - name: Prune
        uses: vlaurin/action-ghcr-prune@main
        with:
          token: ${{ secrets.REGISTRY_TOKEN }}
          #organization: your-org
          container: ghcr-install
          dry-run: true # Dry-run first, then change to `false`
          older-than: 0 # days
          keep-last: 1
          untagged: true
