name: Deploy Docker

# Run workflow on tags starting with v (eg. v2, v1.2.0)
on: workflow_dispatch

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      
      #- name: Build and Push Docker Image
       # uses: docker/build-push-action@v2
        #with:
         # push: true # Will only build if this is not here
          #tags: |
           # ghcr.io/${{ github.repository }}:latest
           
      - name: run docker and push
        run: |
          docker build -f ./Dockerfile . -t test:${{github.run_number}} --build-arg NODE_AUTH_TOKEN=$NODE_AUTH_TOKEN
          docker tag test:${{github.run_number}} ghcr.io/ghcr-install/test:${{github.run_number}}
          docker push ghcr.io/ghcr-install/test:${{github.run_number}}
        shell: bash
          
      - name: list image
        run: |
          docker image ls
        shell: bash
