name: '[RM] Preview'

on: workflow_dispatch

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      
      - name: Delete image
        uses: bots-house/ghcr-delete-image-action@v1.0.0
        with: 
          token: ${{ secrets.REGISTRY_TOKEN }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
          min-versions-to-keep: 1
          #delete-only-pre-release-versions: "true"
